# Generated by Django 2.0.6 on 2018-08-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUtil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_mstr',
            name='login_pwd',
            field=models.CharField(max_length=120),
        ),
    ]
